#test_broken 
fn nested_assert_err(canary: i64) i64 = {
    // TODO: this no longer works since flat_call doesn't have good error handling so you can't rethrow -- May 5
    
    @assert_compile_error {
        @assert_compile_error { valid := x; };  // this assertion fires
    };  // and is caught here
    
    canary
}
